export enum GALLERY_ACTION_TYPES {
  FETCH_FOLDERS_SUCCESS = 'gallery/FETCH_FOLDERS_SUCCESS',
  FETCH_FOLDERS_FAILED = 'gallery/FETCH_FOLDERS_FAILED',
  FETCH_PHOTO_LINKS_START = 'gallery/FETCH_PHOTO_LINKS_START',
  FETCH_PHOTO_LINKS_SUCCESS = 'gallery/FETCH_PHOTO_LINKS_SUCCESS',
  FETCH_PHOTO_LINKS_FAILED = 'gallery/FETCH_PHOTO_LINKS_FAILED',
  CLEAR_PHOTO_LINKS = 'gallery/CLEAR_PHOTO_LINKS',
  SET_PHOTO_DATE = 'gallery/SET_PHOTO_DATE',
  ADD_BONUS = 'gallery/ADD_BONUS',
}
