export enum GALLERY_ACTION_TYPES {
  FETCH_FOLDERS_START = 'gallery/FETCH_FOLDERS_START',
  FETCH_FOLDERS_SUCCESS = 'gallery/FETCH_FOLDERS_SUCCESS',
  FETCH_FOLDERS_FAILED = 'gallery/FETCH_FOLDERS_FAILED',
  FETCH_PHOTO_LINKS = 'gallery/FETCH_PHOTO_LINKS',
}
